// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VpnUIClient is the client API for VpnUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnUIClient interface {
	// ListEngineSpecs returns a list of Virtual Private Network Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (VpnUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type vpnUIClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnUIClient(cc grpc.ClientConnInterface) VpnUIClient {
	return &vpnUIClient{cc}
}

func (c *vpnUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (VpnUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VpnUI_ServiceDesc.Streams[0], "/v1.VpnUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &vpnUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VpnUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type vpnUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *vpnUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vpnUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.VpnUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpnUIServer is the server API for VpnUI service.
// All implementations must embed UnimplementedVpnUIServer
// for forward compatibility
type VpnUIServer interface {
	// ListEngineSpecs returns a list of Virtual Private Network Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, VpnUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedVpnUIServer()
}

// UnimplementedVpnUIServer must be embedded to have forward compatible implementations.
type UnimplementedVpnUIServer struct {
}

func (UnimplementedVpnUIServer) ListEngineSpecs(*ListEngineSpecsRequest, VpnUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedVpnUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedVpnUIServer) mustEmbedUnimplementedVpnUIServer() {}

// UnsafeVpnUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnUIServer will
// result in compilation errors.
type UnsafeVpnUIServer interface {
	mustEmbedUnimplementedVpnUIServer()
}

func RegisterVpnUIServer(s grpc.ServiceRegistrar, srv VpnUIServer) {
	s.RegisterService(&VpnUI_ServiceDesc, srv)
}

func _VpnUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VpnUIServer).ListEngineSpecs(m, &vpnUIListEngineSpecsServer{stream})
}

type VpnUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type vpnUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *vpnUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VpnUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VpnUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VpnUI_ServiceDesc is the grpc.ServiceDesc for VpnUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VpnUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VpnUI",
	HandlerType: (*VpnUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _VpnUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _VpnUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vpn-ui.proto",
}
